### ISSUE TITLE
different number of 'layers' between train dataeset and observed datased

### ISSUE THREAD

**Issue by EwenBurban** [kr-colab/diploSHIC#41]
I’ve generated the train dataset using the Snakemake pipeline aviable in the git repo (diploshic/examples/Snakemake) with few modifications ( i just changed the demographic parameter)

But when i try to use diploSHIC predict the following error append : 

"ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 15, 11, 1), found shape=(None, 12, 11, 1)"

Could you help me with this issue ?

here is the complete report that i got : 

`2022-03-04 10:31:10.745544: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.singularity.d/libs
2022-03-04 10:31:10.745581: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-03-04 10:31:15.166829: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /.singularity.d/libs
2022-03-04 10:31:15.167157: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-03-04 10:31:15.167174: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ecobio1): /proc/driver/nvidia/version does not exist
2022-03-04 10:31:15.167359: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/bin/python
Loaded model from disk
Traceback (most recent call last):
  File "/usr/local/bin/diploSHIC", line 589, in <module>
    preds = model.predict(validation_gen.standardize(testX))
  File "/usr/local/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/site-packages/tensorflow/python/framework/func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/usr/local/lib/python3.10/site-packages/keras/engine/training.py", line 1801, in predict_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/site-packages/keras/engine/training.py", line 1790, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/site-packages/keras/engine/training.py", line 1783, in run_step  **
        outputs = model.predict_step(data)
    File "/usr/local/lib/python3.10/site-packages/keras/engine/training.py", line 1751, in predict_step
        return self(x, training=False)
    File "/usr/local/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.10/site-packages/keras/engine/input_spec.py", line 264, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" is '

    ValueError: Input 0 of layer "model" is incompatible with the layer: expected shape=(None, 15, 11, 1), found shape=(None, 12, 11, 1)`

**Comment by andrewkern** [comment]
i'm guessing this is due to polarization flag not being set correctly. can you give your command line call to `diploschic` so i might help debug this better?

**Comment by andrewkern** [comment]
Hi @EwenBurban -- I'm going to close this thread down cause I haven't heard back from you. Feel free to reopen if the issues remains a blocker.
